// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordReset struct {
	ID        pgtype.UUID      `json:"id"`
	Token     string           `json:"token"`
	IsActive  pgtype.Bool      `json:"is_active"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Url struct {
	ID          pgtype.UUID      `json:"id"`
	OriginalUrl string           `json:"original_url"`
	ShortCode   string           `json:"short_code"`
	ClickCount  pgtype.Int4      `json:"click_count"`
	IsActive    pgtype.Bool      `json:"is_active"`
	UserID      pgtype.UUID      `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID         pgtype.UUID      `json:"id"`
	Email      string           `json:"email"`
	FirstName  string           `json:"first_name"`
	LastName   string           `json:"last_name"`
	Password   string           `json:"password"`
	Role       pgtype.Text      `json:"role"`
	IsVerified pgtype.Bool      `json:"is_verified"`
	IsDeleted  pgtype.Bool      `json:"is_deleted"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type VerificationCode struct {
	ID        pgtype.UUID      `json:"id"`
	Code      string           `json:"code"`
	IsActive  pgtype.Bool      `json:"is_active"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
